# Generated by Django 3.2.9 on 2021-11-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='movies',
        ),
        migrations.AddField(
            model_name='user',
            name='like_movies',
            field=models.ManyToManyField(related_name='like_users', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='recommend_movies',
            field=models.ManyToManyField(related_name='recommend_users', to='movies.Movie'),
        ),
    ]
